### PR TITLE
Update Dropwizard to latest version (1.2.2)

### PR DESCRIPTION
**Pull request by ygaller**
I would like to update dropwizard-bundles with the latest DW version so that the latest version can also be used downstream in dropwizard-swagger

### CODE REVIEW

**Comment by ygaller** [comment]
@jakeswenson Any chance you could merge this so that it's up to date with the latest DW dependencies? Thanks.

**Comment by jakeswenson** [comment]
Thanks for the PR @ygaller. I’ll look and get this merged today!
Sorry for the delay

**Review by jakeswenson — APPROVED** [review]
Thanks for the PR.

**Comment by jakeswenson** [comment]
Merged and released as `1.2.2` 
Build: https://travis-ci.org/paradoxical-io/dropwizard-bundles/builds/353935401
Releases: https://github.com/paradoxical-io/dropwizard-bundles/releases

**Comment by jakeswenson** [comment]
It is atomically [released to maven central now](https://travis-ci.org/paradoxical-io/dropwizard-bundles/builds/353935401#L1473), and should be available but ~11:30AM PDT

**Comment by ygaller** [comment]
Thanks. Seems that Dropwizard already release 1.3.0 since the original PR. Opened a separate PR for that.

**Pull request merged**
